### ISSUE TITLE
Image triggers panic in src/identify.rs:840:15

### ISSUE THREAD

**Issue by Simon-Laux** [dignifiedquire/quircs#1]
This image fails with a panic:
## The image
![Bildschirmfoto vom 2020-06-10 19-13-45](https://user-images.githubusercontent.com/18725968/84392074-263e1d00-abfa-11ea-80f6-690275529666.png)
[img.zip](https://github.com/dignifiedquire/quircs/files/4765115/img.zip)
## The panic
```
target/release/examples/qrtest /home/simon/Bilder/Bildschirmfoto\ vom\ 2020-06-10\ 19-13-45.png
quircs test program
Library version: 0.9.0

                                      Time (ms)        Count   
  Filename                        Load  ID    Total ID    Dec  
-------------------------------------------------------------------------------
thread 'main' panicked at 'index 18446744073709551615 out of range for slice of length 7', src/identify.rs:840:15
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
<details><summary>with backtrace:</summary>

```
$RUST_BACKTRACE=1 target/release/examples/qrtest /home/simon/Bilder/Bildschirmfoto\ vom\ 2020-06-10\ 19-13-45.png
quircs test program
Library version: 0.9.0

                                      Time (ms)        Count   
  Filename                        Load  ID    Total ID    Dec  
-------------------------------------------------------------------------------
thread 'main' panicked at 'index 18446744073709551615 out of range for slice of length 7', src/identify.rs:840:15
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1532
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
  11: rust_begin_unwind
             at src/libstd/panicking.rs:385
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:89
  13: core::slice::slice_index_len_fail
             at src/libcore/slice/mod.rs:2751
  14: quircs::identify::fitness_all
  15: quircs::identify::test_grouping
  16: quircs::identify::<impl quircs::quirc::Quirc>::identify
  17: qrtest::main
  18: std::rt::lang_start::{{closure}}
  19: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  20: std::panicking::try::do_call
             at src/libstd/panicking.rs:297
  21: std::panicking::try
             at src/libstd/panicking.rs:274
  22: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  23: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  24: main
  25: __libc_start_main
  26: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
</details>

**Comment by dignifiedquire** [comment]
Thanks for the report, pushed a fix

**Comment by dignifiedquire** [comment]
output is now as expected

```
quircs test program
Library version: 0.9.0

                                      Time (ms)        Count
  Filename                        Load  ID    Total ID    Dec
-------------------------------------------------------------------------------
  1E856CFA-7204-4D3F-BB1A-0C5A019F5D8F.png  39    12    52    1     1

  Decode successful:
    Version: 1
    ECC level: L
    Mask: 2
    Data type: 4
    Length: 4
    Payload: Ok("help")
    ECI: None
```
