### ISSUE TITLE
Image triggers panic in quircs-0.10.2\src\identify.rs:823:17

### ISSUE THREAD

**Issue by ghtz08** [dignifiedquire/quircs#6]
## Image

![gray](https://github.com/user-attachments/assets/881493b4-1abd-4b71-8404-85d35f7e1333)

## Code

```rust
let img = image::open("gray.png").unwrap().to_luma8();
let mut decoder = quircs::Quirc::default();
decoder.identify(img.width() as usize, img.height() as usize, &img);
```

## Stack Backtrace

```shell
thread 'main' panicked at quircs-0.10.2\src\identify.rs:823:17:
index out of bounds: the len is 41 but the index is 41
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\panicking.rs:665
   1: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\core\src\panicking.rs:74
   2: core::panicking::panic_bounds_check
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\core\src\panicking.rs:276
   3: quircs::identify::fitness_all
             at C:\Users\TanZhou\.cargo\registry\src\index.crates.io-6f17d22bba15001f\quircs-0.10.2\src\identify.rs:823
   4: quircs::identify::jiggle_perspective
             at C:\Users\TanZhou\.cargo\registry\src\index.crates.io-6f17d22bba15001f\quircs-0.10.2\src\identify.rs:866
   5: quircs::identify::setup_qr_perspective
             at C:\Users\TanZhou\.cargo\registry\src\index.crates.io-6f17d22bba15001f\quircs-0.10.2\src\identify.rs:913
   6: quircs::identify::record_qr_grid
             at C:\Users\TanZhou\.cargo\registry\src\index.crates.io-6f17d22bba15001f\quircs-0.10.2\src\identify.rs:1051
   7: quircs::identify::test_neighbours
             at C:\Users\TanZhou\.cargo\registry\src\index.crates.io-6f17d22bba15001f\quircs-0.10.2\src\identify.rs:1100
   8: quircs::identify::test_grouping
             at C:\Users\TanZhou\.cargo\registry\src\index.crates.io-6f17d22bba15001f\quircs-0.10.2\src\identify.rs:1177
   9: quircs::quirc::Quirc::identify
             at C:\Users\TanZhou\.cargo\registry\src\index.crates.io-6f17d22bba15001f\quircs-0.10.2\src\identify.rs:1226
  10: qr_code_tool::main
             at .\src\main.rs:15
  11: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c\library\core\src\ops\function.rs:250
  12: core::hint::black_box
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c\library\core\src\hint.rs:389
```

## Environment

quircs: 0.10.2
rust: stable-x86_64-pc-windows-msvc
rustc: 1.81.0 (eeb90cda1 2024-09-04)
cargo: 1.81.0 (2dbb1af80 2024-08-20)
Windows: Windows 11, 23H2, 22631.4169

**Comment by dignifiedquire** [comment]
So it looks like this image contains a QR code which reports version `41`. Unfortunately, according to https://en.wikipedia.org/wiki/QR_code this version doesn't exist, so I don't quite know how to implement a fix for this.

**Comment by ghtz08** [comment]
Is it possible to add a check to give a friendly error message in this case?

**Comment by upk1997** [comment]
It's caused by accessing `VERSION_DB` without validating version numbers. It should be fine after adding version validation #8 .

**Comment by dignifiedquire** [comment]
Thanks, fixed in `0.10.3`
